# Generated by Django 4.1.7 on 2023-03-08 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymousID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('session_id', models.CharField(max_length=200)),
                ('session_creation_time', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('referrer', models.URLField(max_length=400)),
                ('search', models.CharField(max_length=200)),
            ],
        ),
    ]
