# Generated by Django 4.1.7 on 2023-03-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_browser_page_user_agent_remove_page_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='search',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
