# Generated by Django 4.1.7 on 2023-03-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_path_alter_page_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='session_creation_time',
        ),
        migrations.RemoveField(
            model_name='page',
            name='session_id',
        ),
    ]
