# Generated by Django 4.1.7 on 2023-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_page_session_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='anonymous_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
