# Generated by Django 4.1.7 on 2023-03-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_page_anonymous_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='anonymous_id',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
