# Generated by Django 4.1.7 on 2023-03-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_website_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
