# Generated by Django 4.1.7 on 2023-03-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='hostname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
